# Generated by Django 3.2.8 on 2021-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodoro',
            old_name='create_ad',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='pomodorotree',
            name='current_pomodors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pomodorotree',
            name='time_for_next_pomodoro',
            field=models.IntegerField(default=0),
        ),
    ]
