# Generated by Django 3.2.8 on 2021-10-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211029_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodoro',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
