# Generated by Django 3.2.8 on 2021-10-30 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211030_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_spent', models.IntegerField()),
                ('pomodorotree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pomodorotree')),
            ],
        ),
    ]
