# Generated by Django 3.2.8 on 2021-10-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timespent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedeemedRewards',
        ),
    ]
