# Generated by Django 3.2.8 on 2021-10-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_secretreward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretreward',
            old_name='secret_contet',
            new_name='content',
        ),
    ]
